/**
 * Regenerate fixtures/parity.json from assets/js/forex-core.js.
 *
 *   node tests/gen-parity.mjs
 *
 * The fixture is the contract between the two implementations of the same
 * arithmetic: the JavaScript the website runs, and the PHP the Telegram bot
 * runs. test-forex-core.mjs asserts the JS still matches it; test-bot-math.php
 * asserts the PHP does. Change the maths on either side without regenerating
 * and one of the two suites goes red, which is the entire point.
 *
 * Run this only when the maths is meant to change, and read the diff.
 */
import { createRequire } from 'module';
import { writeFileSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const require = createRequire( import.meta.url );
const F = require( '../assets/js/forex-core.js' );
const here = dirname( fileURLToPath( import.meta.url ) );

export const RATES = { USDINR: 83, USDJPY: 147, EURUSD: 1.165, GBPUSD: 1.34 };

/** Input rows both runtimes evaluate. Keep them boring and varied. */
export const PIP_CASES = [
	[ 'EURUSD', 1 ],
	[ 'EURUSD', 0.1 ],
	[ 'EURUSD', 0.01 ],
	[ 'GBPUSD', 1 ],
	[ 'GBPUSD', 0.01 ],
	[ 'USDJPY', 1 ],
	[ 'USDJPY', 0.01 ],
	[ 'XAUUSD', 1 ],
	[ 'XAUUSD', 0.01 ],
	[ 'USDINR', 1 ],
	[ 'USDINR', 0.05 ],
];

/** pair, lots, price, leverage. Price is ignored for USD-base pairs. */
export const MARGIN_CASES = [
	[ 'EURUSD', 0.05, 1.165, 500 ],
	[ 'EURUSD', 0.05, 1.165, 200 ],
	[ 'EURUSD', 0.05, 1.165, 100 ],
	[ 'EURUSD', 0.01, 1.165, 500 ],
	[ 'GBPUSD', 0.01, 1.34, 500 ],
	[ 'USDJPY', 0.01, 0, 500 ],
	[ 'USDJPY', 1, 0, 100 ],
	[ 'XAUUSD', 0.01, 4650, 500 ],
];

export function build() {
	return {
		note: 'Generated by tests/gen-parity.mjs — do not hand-edit.',
		rates: RATES,
		pip_value: PIP_CASES.map( ( [ pair, lots ] ) => {
			const r = F.pipValue( pair, lots, RATES );
			return { pair, lots, quote: r.quote, usd: r.usd, inr: r.inr };
		} ),
		margin_required: MARGIN_CASES.map( ( [ pair, lots, price, leverage ] ) => {
			const r = F.marginRequired( pair, lots, price, leverage, RATES );
			return {
				pair,
				lots,
				price,
				leverage,
				notional_usd: r.notionalUSD,
				margin_usd: r.marginUSD,
				margin_inr: r.marginINR,
			};
		} ),
	};
}

if ( process.argv[ 1 ] === fileURLToPath( import.meta.url ) ) {
	const out = join( here, 'fixtures' );
	mkdirSync( out, { recursive: true } );
	writeFileSync( join( out, 'parity.json' ), JSON.stringify( build(), null, '\t' ) + '\n' );
	console.log( 'Wrote tests/fixtures/parity.json' );
}
